### ISSUE TITLE
Error de compilación en iOS

### ISSUE THREAD

**Issue by anagac** [alfredoqt/flutter_conekta#1]
Hola, he estado usando la librería para generar los tokens de las tarjetas en mi app con flutter. Funciona muy bien. Solamente que parece haber un problema de compilación con iOS. 

En el archivo FlutterConektaPlugin.m en la función `handleMethodCall`, en el callback de error de la llamada a `createWithSuccess`. Actualmente se quiere hacer un NSLog al objeto `data`, pero dicho objeto no es parte del scope del callback.

`andError:^(NSError* error) {
            NSLog(@"Error data: %@", data);
            result([FlutterError errorWithCode:@"ERROR_UNABLE_TO_TOKENIZE" message:error.localizedDescription details:nil]);
}`

Debería quedar así: 

`andError:^(NSError* error) {
            NSLog(@"Error data: %@", error);
            result([FlutterError errorWithCode:@"ERROR_UNABLE_TO_TOKENIZE" message:error.localizedDescription details:nil]);
}`

Para solucionar el problema tuve que modificar la librería manualmente dentro de mi proyecto, pero dado que colaboro con otras personas, ellos tienen que hacer lo mismo. 

Saludos!

**Comment by alfredoqt** [comment]
Te pido una disculpa por contestar hasta ahorita @anagac . Hoy en la noche queda resuelto. Estaba añadiendo código para mostrar errores relacionados con números de tarjeta incorrecto. Al final decidí no ponerlo puesto que estaba manejando esos errores con otras validaciones en mi aplicación específica. Removí el código en iOS pero no lo probé. Espero que no te haya causado muchas molestias.

**Comment by alfredoqt** [comment]
El issue ha sido resuelto en la versión 1.0.7+1.
