### ISSUE TITLE
UIWebView are no longer accepted. Instead, use WKWebView

### ISSUE THREAD

**Issue by RoboticNotes** [alfredoqt/flutter_conekta#4]
Problems to upload in Apps Store Connect

./.symlinks/plugins/flutter_conekta/ios/Classes/Conekta.m:    UIWebView *web = [[UIWebView alloc] initWithFrame:CGRectMake(0, 0, 0, 0)];

**Comment by IsaacGonzalez** [comment]
Having the same problem.

**Comment by IsaacGonzalez** [comment]
@RoboticNotes I published another package with that issue resolved, if you need it. 

https://pub.dev/packages/flutter_conekta_2

**Comment by RoboticNotes** [comment]
TAL @IsaacGonzalez , I really needed it.
